### PR TITLE
Add initial commit for addin support for kubernetes loadbalancer

### PR DESCRIPTION
**Pull request by mabuaisha**

### CODE REVIEW

**Review by EarthmanT — APPROVED** [review]
Looks good. One question: shouldn't the LB VMs be called k8s_load_host instead of k8s_node_host. And one thought: Shouldn't the LB's all expose a public IP?

**Comment by mabuaisha** [comment]
@EarthmanT I will refactor the name for load balancer node and regrading to the public ip address we can do it but this is how it was implemented before

**Review by 0lvin — COMMENTED** [review]
You can use short version of scripts/kubernetes_loadbalancer/create.py

Without config for kubernetes mount and insert certificates to trusted.

**Review by 0lvin — APPROVED** [review]

**Comment by EarthmanT** [comment]
Use this 4.3 plugin import syntax:
```
  - plugin:cloudify-diamond-plugin
  - plugin:cloudify-fabric-plugin
  - plugin:cloudify-utilities-plugin
  - plugin:cloudify-kubernetes-plugin
  - plugin:cloudify-awssdk-plugin
```

**Comment by mabuaisha** [comment]
@EarthmanT done

**Review by 0lvin — CHANGES_REQUESTED** [review]
We never call mount on loadbalancer, could you please delete all "mount" related functionality.

**Comment by mabuaisha** [comment]
@0lvin done removed the mount changes for load balancer

**Review by 0lvin — APPROVED** [review]
Looks good.

**Pull request merged**
